BIST100_2022_4 = ["AEFES", "AGHOL", "AKBNK", "AKFGY", "AKSA", "AKSEN", "ALARK", "ALBRK", "ALGYO", "ALKIM", "ARCLK", "ASELS", "AYDEM","BAGFS", "BASGZ", "BERA", "BIMAS", "BRYAT", "BUCIM","CCOLA", "CEMTS", "CIMSA","DEVA", "DOAS", "DOHOL","ECILC", "EGEEN", "EKGYO", "ENJSA", "ENKAI", "ERBOS", "EREGL","FROTO","GARAN", "GENIL", "GESAN", "GLYHO", "GOZDE", "GSDHO", "GUBRF", "GWIND", "HALKB", "HEKTS", "IPEKE", "ISCTR", "ISDMR", "ISFIN", "ISGYO", "ISMEN", "JANTS", "KARSN", "KARTN", "KCHOL", "KONTR", "KORDS", "KOZAA", "KOZAL", "KRDMD", "LOGO", "MAVI", "MGROS", "NTHOL", "NUGYO", "ODAS", "OTKAR", "OYAKC", "PETKM", "PGSUS", "PRKAB", "PSGYO", "QUAGR", "SAHOL","SASA","SELEC","SISE","SKBNK","SMRTG","SNGYO","SOKM","TAVHL","TCELL","THYAO","TKFEN","TMSN","TOASO","TRGYO","TSKB","TSPOR","TTKOM","TTRAK","TUKAS","TUPRS","TURSG","ULKER","VAKBN","VESBE","VESTL","YATAS","YKBNK","YYLGD"]
BIST100_2022_3 = ['AEFES', 'AGHOL', 'AKBNK', 'AKFGY', 'AKSA', 'AKSEN', 'ALARK', 'ALBRK', 'ALGYO', 'ALKIM', 'ARCLK', 'ARDYZ', 'ASELS', 'AYDEM', 'BAGFS', 'BASGZ', 'BERA', 'BIMAS', 'BRYAT', 'BUCIM', 'CCOLA', 'CEMTS', 'CIMSA', 'DEVA', 'DOAS', 'DOHOL', 'ECILC', 'EGEEN', 'EKGYO', 'ENJSA', 'ENKAI', 'ERBOS', 'EREGL', 'FROTO', 'GARAN', 'GENIL', 'GLYHO', 'GOZDE', 'GSDHO', 'GUBRF', 'GWIND', 'HALKB', 'HEKTS', 'INDES', 'INVES', 'IPEKE', 'ISCTR', 'ISDMR', 'ISFIN', 'ISGYO', 'ISMEN', 'JANTS', 'KARSN', 'KCHOL', 'KONTR', 'KORDS', 'KOZAA', 'KOZAL', 'KRDMD', 'LOGO', 'MAVI', 'MGROS', 'NTHOL', 'NUGYO', 'ODAS', 'OTKAR', 'OYAKC', 'PARSN', 'PETKM', 'PGSUS', 'PSGYO', 'QUAGR', 'SAHOL', 'SASA', 'SELEC', 'SISE', 'SKBNK', 'SNGYO', 'SOKM', 'TAVHL', 'TCELL', 'THYAO', 'TKFEN', 'TKNSA', 'TOASO', 'TTRAK', 'TRGYO', 'TRILC', 'TSKB', 'TTKOM', 'TUPRS', 'TURSG', 'ULKER', 'VAKBN', 'VESBE', 'VESTL', 'YATAS', 'YKBNK', 'ZOREN', 'ZRGYO']
BIST100_2022_2 = ['AEFES', 'AGHOL', 'AKBNK', 'AKSA', 'AKSEN', 'ALARK', 'ALGYO', 'ALKIM', 'ARASE', 'ARCLK', 'ARDYZ', 'ASELS', 'AYDEM', 'BASGZ', 'BERA', 'BIMAS', 'BIOEN', 'BRISA', 'BRYAT', 'CANTE', 'CCOLA', 'CIMSA', 'DEVA', 'DOAS', 'DOHOL', 'ECILC', 'EGEEN', 'EKGYO', 'ENJSA', 'ENKAI', 'ERBOS', 'EREGL', 'ESEN', 'FROTO', 'GARAN', 'GENIL', 'GLYHO', 'GOZDE', 'GSDHO', 'GUBRF', 'GWIND', 'HALKB', 'HEKTS', 'INDES', 'IPEKE', 'ISCTR', 'ISDMR', 'ISFIN', 'ISGYO', 'ISMEN', 'JANTS', 'KARSN', 'KARTN', 'KCHOL', 'KONTR', 'KORDS', 'KOZAA', 'KOZAL', 'KRDMD', 'KUTPO', 'KZBGY', 'LOGO', 'MAVI', 'MGROS', 'NTHOL', 'NUGYO', 'ODAS', 'OTKAR', 'OYAKC', 'PARSN', 'PETKM', 'PGSUS', 'QUAGR', 'SAHOL', 'SASA', 'SELEC', 'SISE', 'SKBNK', 'SNGYO', 'SOKM', 'TAVHL', 'TCELL', 'THYAO', 'TKFEN', 'TKNSA', 'TOASO', 'TTRAK', 'TRGYO', 'TRILC', 'TSKB', 'TTKOM', 'TUPRS', 'TURSG', 'ULKER', 'VAKBN', 'VESBE', 'VESTL', 'YKBNK', 'ZOREN', 'ZRGYO']
BIST100_2022_1 = ['ADESE', 'AEFES', 'AGHOL', 'AKBNK', 'AKSA', 'AKSEN', 'ALARK', 'ALGYO', 'ALKIM', 'ARCLK', 'ARDYZ', 'ASELS', 'AYDEM', 'BASGZ', 'BERA', 'BIMAS', 'BIOEN', 'BRISA', 'BRYAT', 'CANTE', 'CCOLA', 'CEMAS', 'CIMSA', 'DEVA', 'DOAS', 'DOHOL', 'ECILC', 'EGEEN', 'EKGYO', 'ENJSA', 'ENKAI', 'ERBOS', 'EREGL', 'ESEN', 'FROTO', 'GARAN', 'GENIL', 'GESAN', 'GLYHO', 'GOZDE', 'GUBRF', 'HALKB', 'HEKTS', 'INDES', 'IPEKE', 'ISCTR', 'ISDMR', 'ISFIN', 'ISGYO', 'ISMEN', 'IZMDC', 'KARSN', 'KARTN', 'KCHOL', 'KERVT', 'KORDS', 'KOZAA', 'KOZAL', 'KRDMD', 'KRVGD', 'LOGO', 'MAVI', 'MGROS', 'NTHOL', 'ODAS', 'OTKAR', 'OYAKC', 'PARSN', 'PETKM', 'PGSUS', 'QUAGR', 'RTALB', 'SAHOL', 'SARKY', 'SASA', 'SELEC', 'SISE', 'SKBNK', 'SOKM', 'TAVHL', 'TCELL', 'THYAO', 'TKFEN', 'TKNSA', 'TOASO', 'TTRAK', 'TRGYO', 'TSKB', 'TTKOM', 'TUPRS', 'TURSG', 'ULKER', 'VAKBN', 'VERUS', 'VESBE', 'VESTL', 'YATAS', 'YKBNK', 'ZOREN', 'ZRGYO']
BIST100_2021_4 = ['AEFES', 'AGHOL', 'AKBNK', 'AKCNS', 'AKSA', 'AKSEN', 'ALARK', 'ALBRK', 'ALGYO', 'ALKIM', 'ARCLK', 'ARDYZ', 'ASELS', 'AYDEM', 'AYGAZ', 'BERA', 'BIMAS', 'BIOEN', 'BRISA', 'CANTE', 'CCOLA', 'CEMTS', 'CIMSA', 'DEVA', 'DOAS', 'DOHOL', 'ECILC', 'EGEEN', 'EKGYO', 'ENJSA', 'ENKAI', 'ERBOS', 'EREGL', 'ESEN', 'FROTO', 'GARAN', 'GLYHO', 'GOZDE', 'GUBRF', 'HALKB', 'HEKTS', 'HLGYO', 'INDES', 'ISCTR', 'ISDMR', 'ISFIN', 'ISGYO', 'ISMEN', 'IZMDC', 'KARSN', 'KARTN', 'KCHOL', 'KERVT', 'KORDS', 'KOZAA', 'KOZAL', 'KRDMD', 'KRVGD', 'LOGO', 'MAVI', 'MGROS', 'MPARK', 'NETAS', 'ODAS', 'OTKAR', 'OYAKC', 'PARSN', 'PETKM', 'PGSUS', 'QUAGR', 'SAHOL', 'SARKY', 'SASA', 'SELEC', 'SISE', 'SKBNK', 'SOKM', 'TAVHL', 'TCELL', 'THYAO', 'TKFEN', 'TKNSA', 'TMSN', 'TOASO', 'TTRAK', 'TRGYO', 'TRILC', 'TSKB', 'TTKOM', 'TUPRS', 'TURSG', 'ULKER', 'VAKBN', 'VERUS', 'VESBE', 'VESTL', 'YATAS', 'YKBNK', 'ZOREN', 'ZRGYO']
BIST100_2021_3 = ['AEFES', 'AFYON', 'AKBNK', 'AKSA', 'AKSEN', 'ALARK', 'ALBRK', 'ALGYO', 'ALKIM', 'ARCLK', 'ASELS', 'BERA', 'BIMAS', 'BRISA', 'BRSAN', 'BRYAT', 'CCOLA', 'CEMAS', 'CEMTS', 'CIMSA', 'DEVA', 'DOAS', 'DOHOL', 'ECILC', 'ECZYT', 'EGEEN', 'EGGUB', 'EKGYO', 'ENJSA', 'ENKAI', 'ERBOS', 'EREGL', 'ESEN', 'FENER', 'FROTO', 'GARAN', 'GLYHO', 'GOZDE', 'GSRAY', 'GUBRF', 'HALKB', 'HDFGS', 'HEKTS', 'IHLAS', 'IHLGM', 'INDES', 'IPEKE', 'ISCTR', 'ISFIN', 'ISGYO', 'ISMEN', 'JANTS', 'KARSN', 'KARTN', 'KCHOL', 'KERVT', 'KONYA', 'KORDS', 'KOZAA', 'KOZAL', 'KRDMD', 'KRVGD', 'LOGO', 'MGROS', 'MPARK', 'NETAS', 'NTHOL', 'NUHCM', 'ODAS', 'OTKAR', 'OYAKC', 'PARSN', 'PETKM', 'PGSUS', 'RTALB', 'SAHOL', 'SASA', 'SELEC', 'SISE', 'SKBNK', 'SOKM', 'TAVHL', 'TCELL', 'THYAO', 'TKFEN', 'TKNSA', 'TOASO', 'TTRAK', 'TRGYO', 'TSKB', 'TTKOM', 'TUPRS', 'TURSG', 'ULKER', 'VAKBN', 'VERUS', 'VESBE', 'VESTL', 'YKBNK', 'ZOREN']
BIST100_2021_2 = ['AEFES', 'AKBNK', 'AKSA', 'AKSEN', 'AKSGY', 'ALARK', 'ALBRK', 'ALGYO', 'ALKIM', 'ARCLK', 'ASELS', 'BERA', 'BIMAS', 'BRISA', 'BRSAN', 'BUCIM', 'CCOLA', 'CEMAS', 'CEMTS', 'CIMSA', 'DEVA', 'DOAS', 'DOHOL', 'ECILC', 'ECZYT', 'EGEEN', 'EGGUB', 'EKGYO', 'ENJSA', 'EREGL', 'ESEN', 'FENER', 'FROTO', 'GARAN', 'GOODY', 'GOZDE', 'GSDHO', 'GUBRF', 'HALKB', 'HEKTS', 'HLGYO', 'IHLAS', 'IHLGM', 'INDES', 'IPEKE', 'ISCTR', 'ISFIN', 'ISGYO', 'ISMEN', 'JANTS', 'KARSN', 'KARTN', 'KCHOL', 'KERVT', 'KONYA', 'KORDS', 'KOZAA', 'KOZAL', 'KRDMD', 'KRVGD', 'MAVI', 'MGROS', 'MPARK', 'NETAS', 'NTHOL', 'NUHCM', 'ODAS', 'OTKAR', 'OYAKC', 'PARSN', 'PETKM', 'PGSUS', 'POLHO', 'SAHOL', 'SASA', 'SELEC', 'SISE', 'SKBNK', 'SOKM', 'TATGD', 'TAVHL', 'TCELL', 'THYAO', 'TKFEN', 'TKNSA', 'TOASO', 'TTRAK', 'TRGYO', 'TSKB', 'TTKOM', 'TUKAS', 'TUPRS', 'TURSG', 'ULKER', 'VAKBN', 'VERUS', 'VESTL', 'YATAS', 'YKBNK', 'ZOREN']
BIST100_2021_1 = ['AEFES', 'AGHOL', 'AKBNK', 'AKCNS', 'AKGRT', 'AKSA', 'AKSEN', 'AKSGY', 'ALARK', 'ALBRK', 'ALCTL', 'ALGYO', 'ALKIM', 'ARCLK', 'ASELS', 'AYGAZ', 'BERA', 'BIMAS', 'BIZIM', 'BRISA', 'BRSAN', 'BUCIM', 'CCOLA', 'CEMTS', 'CIMSA', 'DEVA', 'DOAS', 'DOHOL', 'ECILC', 'ECZYT', 'EGEEN', 'EGGUB', 'EKGYO', 'ENJSA', 'ENKAI', 'EREGL', 'FROTO', 'GARAN', 'GOODY', 'GOZDE', 'GSDHO', 'GUBRF', 'HALKB', 'HEKTS', 'HLGYO', 'IHLGM', 'INDES', 'IPEKE', 'ISCTR', 'ISDMR', 'ISFIN', 'ISGYO', 'ISMEN', 'KARSN', 'KARTN', 'KCHOL', 'KERVT', 'KONYA', 'KORDS', 'KOZAA', 'KOZAL', 'KRDMD', 'LOGO', 'MAVI', 'MGROS', 'MPARK', 'NETAS', 'NTHOL', 'ODAS', 'OTKAR', 'OYAKC', 'OZKGY', 'PETKM', 'PGSUS', 'PNSUT', 'SAHOL', 'SASA', 'SELEC', 'SISE', 'SKBNK', 'SOKM', 'TATGD', 'TAVHL', 'TCELL', 'THYAO', 'TKFEN', 'TOASO', 'TTRAK', 'TRGYO', 'TSKB', 'TTKOM', 'TUPRS', 'TURSG', 'ULKER', 'VAKBN', 'VERUS', 'VESTL', 'YATAS', 'YKBNK', 'ZOREN']
BIST100_2020_4 = ['AEFES', 'AGHOL', 'AKBNK', 'AKCNS', 'AKGRT', 'AKSA', 'AKSEN', 'AKSGY', 'ALARK', 'ALBRK', 'ALCTL', 'ALGYO', 'ALKIM', 'ARCLK', 'ARDYZ', 'ASELS', 'AYGAZ', 'BIMAS', 'BIZIM', 'BRISA', 'BRSAN', 'BUCIM', 'CCOLA', 'CEMTS', 'CIMSA', 'CLEBI', 'DEVA', 'DOAS', 'DOCO', 'DOHOL', 'ECILC', 'ECZYT', 'EGEEN', 'EKGYO', 'ENJSA', 'ENKAI', 'EREGL', 'FROTO', 'GARAN', 'GOODY', 'GOZDE', 'GSDHO', 'GUBRF', 'HALKB', 'HEKTS', 'HLGYO', 'INDES', 'IPEKE', 'ISCTR', 'ISDMR', 'ISFIN', 'ISGYO', 'ISMEN', 'KAREL', 'KARTN', 'KCHOL', 'KERVT', 'KORDS', 'KOZAA', 'KOZAL', 'KRDMD', 'LOGO', 'MAVI', 'MGROS', 'MPARK', 'NETAS', 'NTHOL', 'ODAS', 'OTKAR', 'OYAKC', 'OZKGY', 'PETKM', 'PETUN', 'PGSUS', 'PNSUT', 'SAHOL', 'SASA', 'SELEC', 'SISE', 'SKBNK', 'SOKM', 'TATGD', 'TAVHL', 'TCELL', 'THYAO', 'TKFEN', 'TMSN', 'TOASO', 'TRGYO', 'TSKB', 'TTKOM', 'TTRAK', 'TUPRS', 'TURSG', 'ULKER', 'VAKBN', 'VESTL', 'YATAS', 'YKBNK', 'ZOREN']
BIST100_2020_3 = ['AEFES', 'AGHOL', 'AKBNK', 'AKCNS', 'AKGRT', 'AKSA', 'AKSEN', 'ALARK', 'ALBRK', 'ALGYO', 'ALKIM', 'ANACM', 'ARCLK', 'ASELS', 'AYGAZ', 'BIMAS', 'BIZIM', 'BRISA', 'BRSAN', 'BUCIM', 'CCOLA', 'CEMTS', 'CIMSA', 'CLEBI', 'DEVA', 'DOAS', 'DOCO', 'DOHOL', 'ECILC', 'ECZYT', 'EGEEN', 'EKGYO', 'ENJSA', 'ENKAI', 'EREGL', 'FROTO', 'GARAN', 'GLYHO', 'GOODY', 'GOZDE', 'GSDHO', 'GUBRF', 'HALKB', 'HEKTS', 'HLGYO', 'IPEKE', 'ISCTR', 'ISDMR', 'ISFIN', 'ISGYO', 'ISMEN', 'KAREL', 'KARSN', 'KARTN', 'KCHOL', 'KERVT', 'KLMSN', 'KORDS', 'KOZAA', 'KOZAL', 'KRDMD', 'LOGO', 'MAVI', 'MGROS', 'MPARK', 'NETAS', 'NTHOL', 'ODAS', 'OTKAR', 'OYAKC', 'OZKGY', 'PETKM', 'PGSUS', 'SAHOL', 'SASA', 'SELEC', 'SISE', 'SKBNK', 'SODA', 'SOKM', 'TATGD', 'TAVHL', 'TCELL', 'THYAO', 'TKFEN', 'TMSN', 'TOASO', 'TRGYO', 'TRKCM', 'TSKB', 'TTKOM', 'TTRAK', 'TUPRS', 'TURSG', 'ULKER', 'VAKBN', 'VESTL', 'YATAS', 'YKBNK', 'ZOREN']
BIST100_2020_2 = ['AEFES', 'AGHOL', 'AKBNK', 'AKCNS', 'AKGRT', 'AKSA', 'AKSEN', 'ALARK', 'ALBRK', 'ALGYO', 'ALKIM', 'ANACM', 'ANHYT', 'ARCLK', 'ASELS', 'AYGAZ', 'BIMAS', 'BIZIM', 'BRISA', 'BRSAN', 'BUCIM', 'CCOLA', 'CEMTS', 'CIMSA', 'CLEBI', 'DEVA', 'DOAS', 'DOHOL', 'ECILC', 'ECZYT', 'EGEEN', 'EKGYO', 'ENJSA', 'ENKAI', 'EREGL', 'FROTO', 'GARAN', 'GLYHO', 'GOODY', 'GOZDE', 'GUBRF', 'HALKB', 'HEKTS', 'HLGYO', 'IPEKE', 'ISCTR', 'ISDMR', 'ISFIN', 'ISGYO', 'ISMEN', 'KAREL', 'KARSN', 'KARTN', 'KCHOL', 'KERVT', 'KLMSN', 'KORDS', 'KOZAA', 'KOZAL', 'KRDMD', 'LOGO', 'MAVI', 'MGROS', 'MPARK', 'NETAS', 'NTHOL', 'ODAS', 'OTKAR', 'OZKGY', 'PETKM', 'PGSUS', 'RYGYO', 'SAHOL', 'SARKY', 'SASA', 'SELEC', 'SISE', 'SKBNK', 'SODA', 'SOKM', 'TATGD', 'TAVHL', 'TCELL', 'THYAO', 'TKFEN', 'TMSN', 'TOASO', 'TRGYO', 'TRKCM', 'TSKB', 'TTKOM', 'TTRAK', 'TUPRS', 'TURSG', 'ULKER', 'VAKBN', 'VESTL', 'YATAS', 'YKBNK', 'ZOREN']
BIST100_2020_1 = ['AEFES', 'AGHOL', 'AKBNK', 'AKGRT', 'AKSA', 'AKSEN', 'ALARK', 'ALBRK', 'ALGYO', 'ALKIM', 'ANACM', 'ANHYT', 'ARCLK', 'ASELS', 'AYGAZ', 'BIMAS', 'BIZIM', 'BRISA', 'BRSAN', 'BTCIM', 'BUCIM', 'CCOLA', 'CEMTS', 'CIMSA', 'CLEBI', 'DEVA', 'DOAS', 'DOHOL', 'ECILC', 'ECZYT', 'EGEEN', 'EKGYO', 'ENJSA', 'ENKAI', 'ERBOS', 'EREGL', 'FROTO', 'GARAN', 'GOODY', 'GOZDE', 'GSDHO', 'GUBRF', 'HALKB', 'HEKTS', 'HLGYO', 'INDES', 'IPEKE', 'ISCTR', 'ISDMR', 'ISFIN', 'ISGYO', 'ISMEN', 'KAREL', 'KARSN', 'KARTN', 'KCHOL', 'KERVT', 'KLMSN', 'KORDS', 'KOZAA', 'KOZAL', 'KRDMD', 'LOGO', 'MAVI', 'MGROS', 'MPARK', 'NETAS', 'NTHOL', 'ODAS', 'OTKAR', 'PETKM', 'PGSUS', 'SAHOL', 'SARKY', 'SASA', 'SISE', 'SKBNK', 'SODA', 'SOKM', 'TATGD', 'TAVHL', 'TCELL', 'THYAO', 'TKFEN', 'TMSN', 'TOASO', 'TRCAS', 'TRGYO', 'TRKCM', 'TSKB', 'TTKOM', 'TTRAK', 'TUPRS', 'TURSG', 'ULKER', 'VAKBN', 'VESTL', 'YATAS', 'YKBNK', 'ZOREN']
BIST100_2019_4 = ['AEFES', 'AGHOL', 'AKBNK', 'AKSA', 'AKSEN', 'ALARK', 'ALBRK', 'ALGYO', 'ANACM', 'ARCLK', 'ASELS', 'AVOD', 'BERA', 'BIMAS', 'BJKAS', 'CCOLA', 'CEMAS', 'CEMTS', 'CLEBI', 'DEVA', 'DGKLB', 'DOAS', 'DOHOL', 'ECILC', 'EGEEN', 'EKGYO', 'ENJSA', 'ENKAI', 'EREGL', 'FENER', 'FROTO', 'GARAN', 'GEREL', 'GLYHO', 'GOLTS', 'GOZDE', 'GSDHO', 'GSRAY', 'GUBRF', 'HALKB', 'HEKTS', 'HLGYO', 'ICBCT', 'IEYHO', 'IHLAS', 'IHLGM', 'IPEKE', 'ISCTR', 'ISDMR', 'ISFIN', 'ITTFH', 'KARSN', 'KCHOL', 'KERVT', 'KONYA', 'KORDS', 'KOZAA', 'KOZAL', 'KRDMD', 'MAVI', 'METRO', 'MGROS', 'MPARK', 'NETAS', 'NTHOL', 'ODAS', 'OTKAR', 'PARSN', 'PETKM', 'PGSUS', 'POLHO', 'PRKME', 'SAHOL', 'SARKY', 'SASA', 'SISE', 'SKBNK', 'SODA', 'SOKM', 'TAVHL', 'TCELL', 'THYAO', 'TKFEN', 'TMSN', 'TOASO', 'TRGYO', 'TRKCM', 'TSKB', 'TTKOM', 'TTRAK', 'TUKAS', 'TUPRS', 'TURSG', 'ULKER', 'VAKBN', 'VERUS', 'VESTL', 'YATAS', 'YKBNK', 'ZOREN']
BIST100_2019_3 = ['ADESE', 'AEFES', 'AGHOL', 'AKBNK', 'AKSA', 'AKSEN', 'ALARK', 'ALBRK', 'ALGYO', 'ANACM', 'ARCLK', 'ASELS', 'AVOD', 'BERA', 'BIMAS', 'BJKAS', 'CCOLA', 'CEMAS', 'CEMTS', 'CLEBI', 'DGKLB', 'DOHOL', 'ECILC', 'EGEEN', 'EKGYO', 'ENJSA', 'ENKAI', 'EREGL', 'FENER', 'FROTO', 'GARAN', 'GENTS', 'GEREL', 'GOLTS', 'GOZDE', 'GSDHO', 'GSRAY', 'GUBRF', 'HALKB', 'HEKTS', 'HURGZ', 'ICBCT', 'IEYHO', 'IHLAS', 'IHLGM', 'INDES', 'IPEKE', 'ISCTR', 'ISDMR', 'ISFIN', 'ISGYO', 'ITTFH', 'KARSN', 'KCHOL', 'KERVT', 'KONYA', 'KORDS', 'KOZAA', 'KOZAL', 'KRDMD', 'MAVI', 'METRO', 'MGROS', 'MPARK', 'NETAS', 'NTHOL', 'ODAS', 'OTKAR', 'PARSN', 'PETKM', 'PGSUS', 'POLHO', 'PRKME', 'SAHOL', 'SARKY', 'SASA', 'SISE', 'SKBNK', 'SODA', 'SOKM', 'TAVHL', 'TCELL', 'THYAO', 'TKFEN', 'TMSN', 'TOASO', 'TRKCM', 'TSKB', 'TTKOM', 'TTRAK', 'TUKAS', 'TUPRS', 'TURSG', 'ULKER', 'VAKBN', 'VERUS', 'VESTL', 'YATAS', 'YKBNK', 'ZOREN']
BIST100_2019_2 = ['AEFES', 'AKBNK', 'AKSA', 'AKSEN', 'ALARK', 'ALBRK', 'ALGYO', 'ANACM', 'ARCLK', 'ASELS', 'BERA', 'BIMAS', 'BJKAS', 'CCOLA', 'CEMAS', 'CEMTS', 'CLEBI', 'DGKLB', 'DOHOL', 'ECILC', 'EGEEN', 'EKGYO', 'ENJSA', 'ENKAI', 'EREGL', 'FENER', 'FROTO', 'GARAN', 'GENTS', 'GEREL', 'GLYHO', 'GOLTS', 'GOODY', 'GOZDE', 'GSDHO', 'GSRAY', 'GUBRF', 'HALKB', 'HEKTS', 'HURGZ', 'ICBCT', 'IEYHO', 'IHLAS', 'IHLGM', 'INDES', 'IPEKE', 'ISCTR', 'ISDMR', 'ISFIN', 'ISGYO', 'ITTFH', 'KARSN', 'KARTN', 'KCHOL', 'KERVT', 'KORDS', 'KOZAA', 'KOZAL', 'KRDMD', 'MAVI', 'METRO', 'MGROS', 'MPARK', 'NETAS', 'NTHOL', 'ODAS', 'OTKAR', 'PARSN', 'PETKM', 'PGSUS', 'POLHO', 'PRKME', 'SAHOL', 'SARKY', 'SASA', 'SISE', 'SKBNK', 'SODA', 'SOKM', 'TATGD', 'TAVHL', 'TCELL', 'THYAO', 'TKFEN', 'TMSN', 'TOASO', 'TRKCM', 'TSKB', 'TSPOR', 'TTKOM', 'TTRAK', 'TUPRS', 'TURSG', 'ULKER', 'VAKBN', 'VERUS', 'VESTL', 'YATAS', 'YKBNK', 'ZOREN']
BIST100_2020_4 = ['AEFES', 'AKBNK', 'AKSA', 'AKSEN', 'ALARK', 'ALBRK', 'ALGYO', 'ANACM', 'ANELE', 'ARCLK', 'ASELS', 'BERA', 'BIMAS', 'BJKAS', 'CCOLA', 'CEMAS', 'CEMTS', 'CLEBI', 'DEVA', 'DGKLB', 'DOHOL', 'ECILC', 'EGEEN', 'EKGYO', 'ENJSA', 'ENKAI', 'EREGL', 'FENER', 'FLAP', 'FROTO', 'GARAN', 'GENTS', 'GEREL', 'GLYHO', 'GOLTS', 'GOODY', 'GOZDE', 'GSDHO', 'GSRAY', 'GUBRF', 'HALKB', 'HEKTS', 'HURGZ', 'ICBCT', 'IHLAS', 'IHLGM', 'INDES', 'IPEKE', 'ISCTR', 'ISDMR', 'ISGYO', 'ITTFH', 'KARSN', 'KARTN', 'KCHOL', 'KERVT', 'KORDS', 'KOZAA', 'KOZAL', 'KRDMD', 'MAVI', 'METRO', 'MGROS', 'MPARK', 'NETAS', 'NTHOL', 'ODAS', 'OTKAR', 'PARSN', 'PETKM', 'PGSUS', 'POLHO', 'PRKME', 'SAHOL', 'SARKY', 'SASA', 'SISE', 'SKBNK', 'SODA', 'SOKM', 'TATGD', 'TAVHL', 'TCELL', 'THYAO', 'TKFEN', 'TMSN', 'TOASO', 'TRKCM', 'TSKB', 'TTKOM', 'TTRAK', 'TUPRS', 'TURSG', 'ULKER', 'VAKBN', 'VERUS', 'VESTL', 'YATAS', 'YKBNK', 'ZOREN']

YBIST100_2020_4 = [s + ".IS" for s in BIST100_2020_4]

import yfinance as yf

import pandas as pd

SEKTORLER_22_4 = {
    BIST100_2020_4[0]: yf.Ticker(YBIST100_2020_4[0]).info["industry"],
    BIST100_2020_4[1]: yf.Ticker(YBIST100_2020_4[1]).info["industry"],
    BIST100_2020_4[2]: yf.Ticker(YBIST100_2020_4[2]).info["industry"],
    BIST100_2020_4[3]: yf.Ticker(YBIST100_2020_4[3]).info["industry"],
    BIST100_2020_4[4]: yf.Ticker(YBIST100_2020_4[4]).info["industry"],
    BIST100_2020_4[5]: yf.Ticker(YBIST100_2020_4[5]).info["industry"],
    BIST100_2020_4[6]: yf.Ticker(YBIST100_2020_4[6]).info["industry"],
    BIST100_2020_4[7]: yf.Ticker(YBIST100_2020_4[7]).info["industry"],
    BIST100_2020_4[8]: yf.Ticker(YBIST100_2020_4[8]).info["industry"],
    BIST100_2020_4[9]: yf.Ticker(YBIST100_2020_4[9]).info["industry"],
    BIST100_2020_4[10]: yf.Ticker(YBIST100_2020_4[10]).info["industry"],
    BIST100_2020_4[11]: yf.Ticker(YBIST100_2020_4[11]).info["industry"],
    BIST100_2020_4[12]: yf.Ticker(YBIST100_2020_4[12]).info["industry"],
    BIST100_2020_4[13]: yf.Ticker(YBIST100_2020_4[13]).info["industry"],
    BIST100_2020_4[14]: yf.Ticker(YBIST100_2020_4[14]).info["industry"],
    BIST100_2020_4[15]: yf.Ticker(YBIST100_2020_4[15]).info["industry"],
    BIST100_2020_4[16]: yf.Ticker(YBIST100_2020_4[16]).info["industry"],
    BIST100_2020_4[17]: yf.Ticker(YBIST100_2020_4[17]).info["industry"],
    BIST100_2020_4[18]: yf.Ticker(YBIST100_2020_4[18]).info["industry"],
    BIST100_2020_4[19]: yf.Ticker(YBIST100_2020_4[19]).info["industry"],
    BIST100_2020_4[20]: yf.Ticker(YBIST100_2020_4[20]).info["industry"],
    BIST100_2020_4[21]: yf.Ticker(YBIST100_2020_4[21]).info["industry"],
    BIST100_2020_4[22]: yf.Ticker(YBIST100_2020_4[22]).info["industry"],
    BIST100_2020_4[23]: yf.Ticker(YBIST100_2020_4[23]).info["industry"],
    BIST100_2020_4[24]: yf.Ticker(YBIST100_2020_4[24]).info["industry"],
    BIST100_2020_4[25]: yf.Ticker(YBIST100_2020_4[25]).info["industry"],
    BIST100_2020_4[26]: yf.Ticker(YBIST100_2020_4[26]).info["industry"],
    BIST100_2020_4[27]: yf.Ticker(YBIST100_2020_4[27]).info["industry"],
    BIST100_2020_4[28]: yf.Ticker(YBIST100_2020_4[28]).info["industry"],
    BIST100_2020_4[29]: yf.Ticker(YBIST100_2020_4[29]).info["industry"],
    BIST100_2020_4[30]: yf.Ticker(YBIST100_2020_4[30]).info["industry"],
    BIST100_2020_4[31]: yf.Ticker(YBIST100_2020_4[31]).info["industry"],
    BIST100_2020_4[32]: yf.Ticker(YBIST100_2020_4[32]).info["industry"],
    BIST100_2020_4[33]: yf.Ticker(YBIST100_2020_4[33]).info["industry"],
    BIST100_2020_4[34]: yf.Ticker(YBIST100_2020_4[34]).info["industry"],
    BIST100_2020_4[35]: yf.Ticker(YBIST100_2020_4[35]).info["industry"],
    BIST100_2020_4[36]: yf.Ticker(YBIST100_2020_4[36]).info["industry"],
    BIST100_2020_4[37]: yf.Ticker(YBIST100_2020_4[37]).info["industry"],
    BIST100_2020_4[38]: yf.Ticker(YBIST100_2020_4[38]).info["industry"],
    BIST100_2020_4[39]: yf.Ticker(YBIST100_2020_4[39]).info["industry"],
    BIST100_2020_4[40]: yf.Ticker(YBIST100_2020_4[40]).info["industry"],
    BIST100_2020_4[41]: yf.Ticker(YBIST100_2020_4[41]).info["industry"],
    BIST100_2020_4[42]: yf.Ticker(YBIST100_2020_4[42]).info["industry"],
    BIST100_2020_4[43]: yf.Ticker(YBIST100_2020_4[43]).info["industry"],
    BIST100_2020_4[44]: yf.Ticker(YBIST100_2020_4[44]).info["industry"],
    BIST100_2020_4[45]: yf.Ticker(YBIST100_2020_4[45]).info["industry"],
    BIST100_2020_4[46]: yf.Ticker(YBIST100_2020_4[46]).info["industry"],
    BIST100_2020_4[47]: yf.Ticker(YBIST100_2020_4[47]).info["industry"],
    BIST100_2020_4[48]: yf.Ticker(YBIST100_2020_4[48]).info["industry"],
    BIST100_2020_4[49]: yf.Ticker(YBIST100_2020_4[49]).info["industry"],
    BIST100_2020_4[50]: yf.Ticker(YBIST100_2020_4[50]).info["industry"],
    BIST100_2020_4[51]: yf.Ticker(YBIST100_2020_4[51]).info["industry"],
    BIST100_2020_4[52]: yf.Ticker(YBIST100_2020_4[52]).info["industry"],
    BIST100_2020_4[53]: yf.Ticker(YBIST100_2020_4[53]).info["industry"],
    BIST100_2020_4[54]: yf.Ticker(YBIST100_2020_4[54]).info["industry"],
    BIST100_2020_4[55]: yf.Ticker(YBIST100_2020_4[55]).info["industry"],
    BIST100_2020_4[56]: yf.Ticker(YBIST100_2020_4[56]).info["industry"],
    BIST100_2020_4[57]: yf.Ticker(YBIST100_2020_4[57]).info["industry"],
    BIST100_2020_4[58]: yf.Ticker(YBIST100_2020_4[58]).info["industry"],
    BIST100_2020_4[59]: yf.Ticker(YBIST100_2020_4[59]).info["industry"],
    BIST100_2020_4[60]: yf.Ticker(YBIST100_2020_4[60]).info["industry"],
    BIST100_2020_4[61]: yf.Ticker(YBIST100_2020_4[61]).info["industry"],
    BIST100_2020_4[62]: yf.Ticker(YBIST100_2020_4[62]).info["industry"],
    BIST100_2020_4[63]: yf.Ticker(YBIST100_2020_4[63]).info["industry"],
    BIST100_2020_4[64]: yf.Ticker(YBIST100_2020_4[64]).info["industry"],
    BIST100_2020_4[65]: yf.Ticker(YBIST100_2020_4[65]).info["industry"],
    BIST100_2020_4[66]: yf.Ticker(YBIST100_2020_4[66]).info["industry"],
    BIST100_2020_4[67]: yf.Ticker(YBIST100_2020_4[67]).info["industry"],
    BIST100_2020_4[68]: yf.Ticker(YBIST100_2020_4[68]).info["industry"],
    BIST100_2020_4[69]: yf.Ticker(YBIST100_2020_4[69]).info["industry"],
    BIST100_2020_4[70]: yf.Ticker(YBIST100_2020_4[70]).info["industry"],
    BIST100_2020_4[71]: yf.Ticker(YBIST100_2020_4[71]).info["industry"],
    BIST100_2020_4[72]: yf.Ticker(YBIST100_2020_4[72]).info["industry"],
    BIST100_2020_4[73]: yf.Ticker(YBIST100_2020_4[73]).info["industry"],
    BIST100_2020_4[74]: yf.Ticker(YBIST100_2020_4[74]).info["industry"],
    BIST100_2020_4[75]: yf.Ticker(YBIST100_2020_4[75]).info["industry"],
    BIST100_2020_4[76]: yf.Ticker(YBIST100_2020_4[76]).info["industry"],
    BIST100_2020_4[77]: yf.Ticker(YBIST100_2020_4[77]).info["industry"],
    BIST100_2020_4[78]: yf.Ticker(YBIST100_2020_4[78]).info["industry"],
    BIST100_2020_4[79]: yf.Ticker(YBIST100_2020_4[79]).info["industry"],
    BIST100_2020_4[80]: yf.Ticker(YBIST100_2020_4[80]).info["industry"],
    BIST100_2020_4[81]: yf.Ticker(YBIST100_2020_4[81]).info["industry"],
    BIST100_2020_4[82]: yf.Ticker(YBIST100_2020_4[82]).info["industry"],
    BIST100_2020_4[83]: yf.Ticker(YBIST100_2020_4[83]).info["industry"],
    BIST100_2020_4[84]: yf.Ticker(YBIST100_2020_4[84]).info["industry"],
    BIST100_2020_4[85]: yf.Ticker(YBIST100_2020_4[85]).info["industry"],
    BIST100_2020_4[86]: yf.Ticker(YBIST100_2020_4[86]).info["industry"],
    BIST100_2020_4[87]: yf.Ticker(YBIST100_2020_4[87]).info["industry"],
    BIST100_2020_4[88]: yf.Ticker(YBIST100_2020_4[88]).info["industry"],
    BIST100_2020_4[89]: yf.Ticker(YBIST100_2020_4[89]).info["industry"],
    BIST100_2020_4[90]: yf.Ticker(YBIST100_2020_4[90]).info["industry"],
    BIST100_2020_4[91]: yf.Ticker(YBIST100_2020_4[91]).info["industry"],
    BIST100_2020_4[92]: yf.Ticker(YBIST100_2020_4[92]).info["industry"],
    BIST100_2020_4[93]: yf.Ticker(YBIST100_2020_4[93]).info["industry"],
    BIST100_2020_4[94]: yf.Ticker(YBIST100_2020_4[94]).info["industry"],
    BIST100_2020_4[95]: yf.Ticker(YBIST100_2020_4[95]).info["industry"],
    BIST100_2020_4[96]: yf.Ticker(YBIST100_2020_4[96]).info["industry"],
    BIST100_2020_4[97]: yf.Ticker(YBIST100_2020_4[97]).info["industry"],
    BIST100_2020_4[98]: yf.Ticker(YBIST100_2020_4[98]).info["industry"],
    BIST100_2020_4[99]: yf.Ticker(YBIST100_2020_4[99]).info["industry"]
    }
SEKTORLERDF = pd.DataFrame(list(SEKTORLER_22_4.items()), columns=("HISSE", "INDUSTRY"))

yol = r"C:\Users\emrec\Desktop\TUBITAK 22 DOSYASI\BIST100_2020_4_industryS.csv"

SEKTORLERDF.to_csv(yol)

#pd.read_csv("verinin pcdeki yolu", index_col=0)